image: python:3.9

stages:
  - lint
  - build
  - push

lint:
  stage: lint
  script:
    - python -m flake8 .

build:
  stage: build
  script:
    - docker build -t my-image .

push:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push my-image
  only:
    - master
